#: warehouse/accounts/forms.py:46
msgid "The password is invalid. Try again."
msgstr ""

#: warehouse/accounts/forms.py:58
msgid "No user found with that username"
msgstr ""

#: warehouse/accounts/forms.py:69
msgid "TOTP code must be ${totp_length} digits."
msgstr ""

#: warehouse/accounts/forms.py:90
msgid "Recovery Codes must be ${recovery_code_length} characters."
msgstr ""

#: warehouse/accounts/forms.py:105
msgid "Choose a username with 50 characters or less."
msgstr ""

#: warehouse/accounts/forms.py:111
msgid ""
"The username is invalid. Usernames must be composed of letters, numbers, "
"dots, hyphens and underscores. And must also start and finish with a "
"letter or number. Choose a different username."
msgstr ""

#: warehouse/accounts/forms.py:128
msgid ""
"This username is already being used by another account. Choose a "
"different username."
msgstr ""

#: warehouse/accounts/forms.py:142 warehouse/accounts/forms.py:186
#: warehouse/accounts/forms.py:199
msgid "Password too long."
msgstr ""

#: warehouse/accounts/forms.py:172 warehouse/accounts/views.py:95
msgid "There have been too many unsuccessful login attempts. Try again later."
msgstr ""

#: warehouse/accounts/forms.py:202
msgid "Your passwords don't match. Try again."
msgstr ""

#: warehouse/accounts/forms.py:233 warehouse/accounts/forms.py:244
msgid "The email address isn't valid. Try again."
msgstr ""

#: warehouse/accounts/forms.py:252
msgid "You can't use an email address from this domain. Use a different email."
msgstr ""

#: warehouse/accounts/forms.py:263
msgid ""
"This email address is already being used by this account. Use a different"
" email."
msgstr ""

#: warehouse/accounts/forms.py:270
msgid ""
"This email address is already being used by another account. Use a "
"different email."
msgstr ""

#: warehouse/accounts/forms.py:292
msgid "The name is too long. Choose a name with 100 characters or less."
msgstr ""

#: warehouse/accounts/forms.py:380
msgid "Invalid TOTP code."
msgstr ""

#: warehouse/accounts/forms.py:397
msgid "Invalid WebAuthn assertion: Bad payload"
msgstr ""

#: warehouse/accounts/forms.py:455
msgid "Invalid recovery code."
msgstr ""

#: warehouse/accounts/forms.py:463
msgid "Recovery code has been previously used."
msgstr ""

#: warehouse/accounts/forms.py:482
msgid "No user found with that username or email"
msgstr ""

#: warehouse/accounts/views.py:112
msgid ""
"Too many emails have been added to this account without verifying them. "
"Check your inbox and follow the verification links. (IP: ${ip})"
msgstr ""

#: warehouse/accounts/views.py:124
msgid ""
"Too many password resets have been requested for this account without "
"completing them. Check your inbox and follow the verification links. (IP:"
" ${ip})"
msgstr ""

#: warehouse/accounts/views.py:264 warehouse/accounts/views.py:328
#: warehouse/accounts/views.py:330 warehouse/accounts/views.py:357
#: warehouse/accounts/views.py:359 warehouse/accounts/views.py:425
msgid "Invalid or expired two factor login."
msgstr ""

#: warehouse/accounts/views.py:322
msgid "Already authenticated"
msgstr ""

#: warehouse/accounts/views.py:401
msgid "Successful WebAuthn assertion"
msgstr ""

#: warehouse/accounts/views.py:455
msgid "Recovery code accepted. The supplied code cannot be used again."
msgstr ""

#: warehouse/accounts/views.py:541
msgid ""
"New user registration temporarily disabled. See https://pypi.org/help"
"#admin-intervention for details."
msgstr ""

#: warehouse/accounts/views.py:670
msgid "Expired token: request a new password reset link"
msgstr ""

#: warehouse/accounts/views.py:672
msgid "Invalid token: request a new password reset link"
msgstr ""

#: warehouse/accounts/views.py:674 warehouse/accounts/views.py:773
#: warehouse/accounts/views.py:872 warehouse/accounts/views.py:1041
msgid "Invalid token: no token supplied"
msgstr ""

#: warehouse/accounts/views.py:678
msgid "Invalid token: not a password reset token"
msgstr ""

#: warehouse/accounts/views.py:683
msgid "Invalid token: user not found"
msgstr ""

#: warehouse/accounts/views.py:694
msgid "Invalid token: user has logged in since this token was requested"
msgstr ""

#: warehouse/accounts/views.py:712
msgid ""
"Invalid token: password has already been changed since this token was "
"requested"
msgstr ""

#: warehouse/accounts/views.py:741
msgid "You have reset your password"
msgstr ""

#: warehouse/accounts/views.py:769
msgid "Expired token: request a new email verification link"
msgstr ""

#: warehouse/accounts/views.py:771
msgid "Invalid token: request a new email verification link"
msgstr ""

#: warehouse/accounts/views.py:777
msgid "Invalid token: not an email verification token"
msgstr ""

#: warehouse/accounts/views.py:786
msgid "Email not found"
msgstr ""

#: warehouse/accounts/views.py:789
msgid "Email already verified"
msgstr ""

#: warehouse/accounts/views.py:806
msgid "You can now set this email as your primary address"
msgstr ""

#: warehouse/accounts/views.py:810
msgid "This is your primary address"
msgstr ""

#: warehouse/accounts/views.py:815
msgid "Email address ${email_address} verified. ${confirm_message}."
msgstr ""

#: warehouse/accounts/views.py:868
msgid "Expired token: request a new organization invitation"
msgstr ""

#: warehouse/accounts/views.py:870
msgid "Invalid token: request a new organization invitation"
msgstr ""

#: warehouse/accounts/views.py:876
msgid "Invalid token: not an organization invitation token"
msgstr ""

#: warehouse/accounts/views.py:880
msgid "Organization invitation is not valid."
msgstr ""

#: warehouse/accounts/views.py:889
msgid "Organization invitation no longer exists."
msgstr ""

#: warehouse/accounts/views.py:940
msgid "Invitation for '${organization_name}' is declined."
msgstr ""

#: warehouse/accounts/views.py:1003
msgid "You are now ${role} of the '${organization_name}' organization."
msgstr ""

#: warehouse/accounts/views.py:1037
msgid "Expired token: request a new project role invitation"
msgstr ""

#: warehouse/accounts/views.py:1039
msgid "Invalid token: request a new project role invitation"
msgstr ""

#: warehouse/accounts/views.py:1045
msgid "Invalid token: not a collaboration invitation token"
msgstr ""

#: warehouse/accounts/views.py:1049
msgid "Role invitation is not valid."
msgstr ""

#: warehouse/accounts/views.py:1064
msgid "Role invitation no longer exists."
msgstr ""

#: warehouse/accounts/views.py:1095
msgid "Invitation for '${project_name}' is declined."
msgstr ""

#: warehouse/accounts/views.py:1162
msgid "You are now ${role} of the '${project_name}' project."
msgstr ""

#: warehouse/accounts/views.py:1418
msgid ""
"You must have a verified email in order to register a pending OpenID "
"Connect publisher. See https://pypi.org/help#openid-connect for details."
msgstr ""

#: warehouse/accounts/views.py:1431
msgid "You can't register more than 3 pending OpenID Connect publishers at once."
msgstr ""

#: warehouse/accounts/views.py:1447
msgid ""
"There have been too many attempted OpenID Connect registrations. Try "
"again later."
msgstr ""

#: warehouse/accounts/views.py:1475
msgid ""
"This OpenID Connect publisher has already been registered. Please contact"
" PyPI's admins if this wasn't intentional."
msgstr ""

#: warehouse/views.py:140
msgid ""
"Two-factor authentication must be enabled on your account to perform this"
" action."
msgstr ""

#: warehouse/views.py:265
msgid "Locale updated"
msgstr ""

